### ISSUE TITLE
Segfault with car demo sample when exiting

### ISSUE THREAD

**Issue by Ev1lbl0w** [GameDevTecnico/cubos#155]
A segfault is happening every time when exiting the car demo sample _(branch [`demo-ecs`](https://github.com/GameDevTecnico/cubos/tree/demo-ecs), both ECS and original versions)_.

Backtrace:
```
#0  0x00007febd8266e60 in ?? ()
#1  0x000056217c329d79 in OGLSampler::~OGLSampler (this=0x56217d18ea90, __in_chrg=<optimized out>) at /home/ricardo/Universidade/GameDev Tecnico/Projects/CUBOS./core/src/cubos/core/gl/ogl_render_device.cpp:500
#2  0x000056217c33f5e0 in std::destroy_at<OGLSampler> (__location=0x56217d18ea90) at /usr/include/c++/11.2.0/bits/stl_construct.h:88
#3  0x000056217c33f25c in std::allocator_traits<std::allocator<OGLSampler> >::destroy<OGLSampler> (__a=..., __p=0x56217d18ea90) at /usr/include/c++/11.2.0/bits/alloc_traits.h:533
#4  0x000056217c33e827 in std::_Sp_counted_ptr_inplace<OGLSampler, std::allocator<OGLSampler>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x56217d18ea80) at /usr/include/c++/11.2.0/bits/shared_ptr_base.h:528
#5  0x000056217c2c902d in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x56217d18ea80) at /usr/include/c++/11.2.0/bits/shared_ptr_base.h:168
#6  0x000056217c2c5dfb in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7ffebf1b97f8, __in_chrg=<optimized out>) at /usr/include/c++/11.2.0/bits/shared_ptr_base.h:705
#7  0x000056217c2c5386 in std::__shared_ptr<cubos::core::gl::impl::Sampler, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7ffebf1b97f0, __in_chrg=<optimized out>) at /usr/include/c++/11.2.0/bits/shared_ptr_base.h:1154
#8  0x000056217c2c53a2 in std::shared_ptr<cubos::core::gl::impl::Sampler>::~shared_ptr (this=0x7ffebf1b97f0, __in_chrg=<optimized out>) at /usr/include/c++/11.2.0/bits/shared_ptr.h:122
#9  0x000056217c2c53d0 in cubos::engine::gl::pps::CopyPass::~CopyPass (this=0x7ffebf1b97c0, __in_chrg=<optimized out>) at /home/ricardo/Universidade/GameDev Tecnico/Projects/CUBOS./engine/include/cubos/engine/gl/pps/copy_pass.hpp:9
#10 0x000056217c2c15b7 in main () at /home/ricardo/Universidade/GameDev Tecnico/Projects/CUBOS./engine/samples/car.cpp:370
```
Seems to happen when objects are being deleted, specifically at this destructor at `gl_render_device.cpp:500`
https://github.com/GameDevTecnico/cubos/blob/115e932d4444c385f75e410d927ab6133db83e9d/core/src/cubos/core/gl/ogl_render_device.cpp#L498-L501

**Comment by Ev1lbl0w** [comment]
Has been fixed in the meantime. closing...
